# Generated by Django 3.1.3 on 2022-02-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FilePathField(default='', path='D:\\djngo projects\\portfolio\\simple\\New folder\\Portfolio-website-using-django-main\\myportfolio/static/img'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(default='', path='D:\\djngo projects\\portfolio\\simple\\New folder\\Portfolio-website-using-django-main\\myportfolio/static/img'),
        ),
    ]
