# Generated by Django 3.1.3 on 2022-02-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_auto_20220210_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
