# Generated by Django 3.1.3 on 2022-02-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_auto_20220210_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='link',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.FilePathField(default='', path='D:\\djngo projects\\portfolio\\simple\\New folder\\Portfolio-website-using-django-main\\myportfolio/static/img'),
        ),
    ]
