# Generated by Django 3.1.3 on 2022-02-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0005_auto_20220212_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
